name: Manual Android APK Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Ambil source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Java (wajib untuk Android)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # 4. Permission gradlew
      - name: Make gradlew executable
        run: chmod +x gradlew

      # 5. Build APK (debug)
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # 6. Upload hasil APK
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: PumpkinMCGui-debug-apk
          path: app/build/outputs/apk/debug/*.apk
